# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: scHiCluster
author: Jingtian Zhou
# logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/zhoujt1994/scHiCluster  # Online location of your book
  path_to_book: docs/schicluster  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
    extra_extensions: # A list of extra extensions to load by Sphinx (added to those already used by JB).
        - "sphinx.ext.autodoc"
        - "sphinx.ext.napoleon"
        - "sphinx.ext.viewcode"
        - "sphinx.ext.intersphinx"
        - "autoapi.extension"
        - "myst_nb"
        - "sphinx_codeautolink"
    local_extensions: # A list of local extensions to load by sphinx specified by "name: path" items
    config: # key-value pairs to directly over-ride the Sphinx configuration
        add_module_names: false
        html_js_files:
            - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
        bibtex_reference_style: author_year
        autoapi_dirs:
            - "../../schicluster"
        autoapi_root: "api"
        autoapi_add_toctree_entry: false
        autoapi_keep_files: false
        autoapi_options:
            - "members"
            - "undoc-members"
            - "private-members"
            - "show-inheritance"
            - "special-members"
            - "imported-members"
